version: '3.8'

volumes:
  mysql-data:

networks:
  grafana-lab-net:
  
services:
  flask-app:
    build: .
    container_name: flask-irs-app
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: mysql-db
      MYSQL_USER: irs_user
      MYSQL_PASSWORD: password123
      MYSQL_DATABASE: irs_data
    
    depends_on:
      - mysql-db
    command: ["sh", "-c", "until nc -z mysql-db 3306; do echo 'Waiting for MySQL...'; sleep 2; done; python generate_data.py && python app.py"]

  mysql-db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: irs_data
      MYSQL_USER: irs_user
      MYSQL_PASSWORD: password123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
